### ISSUE TITLE
How to create a RemoteDocker object?

### ISSUE THREAD

**Issue by rwmajor2** [amihaiemil/docker-java-api#147]
I am using IntelliJ and created a simple mvn Java app.  I have the following code.  However, it is giving me an error that RemoteDocker is not public and I can't use it.  Any thoughts on how to make this work?  I am just testing right now.

```java
import com.amihaiemil.docker.Container;
import com.amihaiemil.docker.Containers;
import com.amihaiemil.docker.RemoteDocker;
import com.amihaiemil.docker.Docker;

public class dockertest {
    public static void main (String args[]) {

        final Docker docker = new RemoteDocker(
                "tcp://127.0.0.1:2375");
        final Containers containers = docker.containers();
        for(final Container container : containers) {
            //Containers is the entry point of the Containers API
            //and also implements Iterable<Container>
        }
    }
}

```

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@rwmajor2[/z](https://www.0crat.com/u/rwmajor2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@rwmajor2 Hello, thanks for the ticket. 

``RemoteDocker`` is not yet public because it hasn't been properly tested yet (I still have to figure out how to do this on Travis). It should work just as fine as ``LocalDocker`` since they use the same classes, it's just a matter of (secure) connection. 

As you can [see](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/RemoteDocker.java#L54) the ctor has changed a bit, in the wiki there was just an initial idea.

The idea with RemoteDocker now is that you have to provision a remote Docker host and when you do so, you should get 3 ``.pem`` files: ``ca.pem``, ``cert.pem`` and ``key.pem``. 

You need to add these 3 files to 2 Java KeyStores (.jks): the first 2 in a ``truststore.jks`` and the key to a ``keystore.jks``. After you have these stores, you need to provide their ``Path`` to ``RemoteDocker`` constructor, as well as password of the keystore and the passphrase of the key (which is within that keystore). 

Sounds a bit complex, but the reasoning is that those certs are already most likely inside Java keystores if they are supposed to be used by a Java application. Besides, reading the ``.pem`` files ourselves would have meant using a 3rd party lib for reading ``.pem``, thus making this library heavier. 

Nevertheless, don't struggle with that, it might not even work. First, try to use ``LocalDocker`` on localhost and see if you can do what you need with the current version. It is still young, not implementing everything (only Images and Containers are partially implemented).

**Comment by amihaiemil** [comment]
@rwmajor2 I forgot to mention: in order to try to use ``RemoteDocker`` you have to fork the repo and make the build yourself. Just ``mvn clean install`` should do the trick with no problems.

**Comment by amihaiemil** [comment]
@rwmajor2 FYI, I just released version ``0.0.3``. RemoteDocker is now public and can be instantiated if you pass it your own ``HttpClient``.

I figured, in the early stages, we should let the users configure their own clients and not assume Docker's place in the network and things such as authentication mechanisms.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#147` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
