### ISSUE TITLE
LocalDockerTestCase.java:39-42: Implement a unix socket...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#38]
The puzzle `39-a863f6f1` from #39 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/27a9d3a333c9778eb6b01e038193bd353b29a8ad/src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java#L39-L42

The puzzle was created by amihaiemil on 11-Mar-18. 

Estimate: 60 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by llorllale** [comment]
@amihaiemil I'm wondering why have `LocalDocker` at all? What do you think of just having `RtDocker` and the *user* can pass either `UnixHttpClient` or some other "regular" client? This way, instead of spinning up a socket server for tests, you could just implement an `HttpClient` that performs the assertions that this task seems to require.

This route just looks easier to my eyes.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@llorllale ``LocalDocker`` and ``RemoteDocker`` have 2 roles: 

1. They offer more semantics
2. They hide the HttpClient. 

Ideally, the user should know nothing about HttpClient, shouldn't even see it. Because Apache HttpClient is a very complex library, I don't want to confuse our users... 

I mean, for ``RemoteDocker``, I think we could expose a ctor which accepts ``HttpClient``, maybe someone who really knows what they are doing could tune it up, make it better.

However, for ``LocalDocker``, the user should really not see any ``HttpClient`` -- there is no real reason to tune it up since it is all on localhost + they should always remember to build an HttpClient and pass a unix socket connection factory etc.

But about testing, you are right, we could have a package-protected ctor in ``LocalDocker``, that would accept HttpClient, so we can pass one mock for testing. 

Can you do that here?

**Comment by amihaiemil** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/amihaiemil/docker-java-api/issues/38#issuecomment-372593328))

@amihaiemil Job [#38](https://github.com/amihaiemil/docker-java-api/issues/38) is now in scope, role is `DEV`

**Comment by amihaiemil** [comment]
@0crat assign @llorllale

**Comment by 0crat** [comment]
The job [#38](https://github.com/amihaiemil/docker-java-api/issues/38) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/720906434). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
> @0crat assign @llorllale  ([here](https://github.com/amihaiemil/docker-java-api/issues/38#issuecomment-372594020))

@amihaiemil Job [#38](https://github.com/amihaiemil/docker-java-api/issues/38) is already assigned to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by amihaiemil** [comment]
@llorllale don't forget PDD, we want to move faster in this project, but still: small PR, unit tests are a priority etc. In this ticket, I would add that default ctor to LocalDocker, modify the other 2 ctors to call it (according to the rule of only one primary ctor) and modify this puzzle, to reflect only the requirement for testing ``UnixHttpClient``. 

If you have time in those 30min, maybe you can also start implementing the mock HttpClient we need for unit testing. I initially figured we could use anonymous classes in the tests, but HttpClient is a very big interface, it would be very ugly.

**Comment by llorllale** [comment]
@amihaiemil can we use cactoos as a dependency?

**Comment by amihaiemil** [comment]
@llorllale no, sorry.

1. I don't like it, as we talked in the past maybe. I like OOP, but rewriting the JDK and other existing libraries is a little absurd. 

2. I have no idea how to use it and don't have time to learn it. Especially since it's in beta version and APIs change a lor.

3. Since this is a library, it has to be as thin as possible, I wouldn't bring in cactoos since it doesn't offer added value, other than redesigned interfaces. :)

But do you need it to solve this Issue? I think not.

**Comment by llorllale** [comment]
@amihaiemil no I don't need it. I just like using it. We've never talked about it before. I think your 3rd point is especially valid.

**Comment by 0pdd** [comment]
The puzzle `39-a863f6f1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd these puzzles are still not solved: [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42).

**Comment by amihaiemil** [comment]
@llorllale apperently, the 0crat's Github API quota is reached and we have to wait until it resets: 

![image](https://user-images.githubusercontent.com/6305156/37351482-d7c89288-26e3-11e8-986c-7b918a556bd1.png)


The past few dozen calls are the same :(

**Comment by amihaiemil** [comment]
@0crat status

**Comment by llorllale** [comment]
@amihaiemil btw I think you may have configured this project's name wrong in 0crat? This is the PM I received from 0crat:

> You got +30 points in the job #38 (https://github.com/amihaiemil/docker-java-api/issues/38) in G6LPQQV2P, your total is +895 (https://www.0crat.com/u/llorllale/awards), see §18 (http://www.zerocracy.com/policy.html#18): Order was finished

**Comment by amihaiemil** [comment]
@llorllale well, at least you got paid, 0crat said nothing here :(

Anyway, I think the issue is that, initially, the project did not have a title, only that ID. 0crat tried to set the title to be the same as the name of the Slack private chat. Problem was that the channel's name was too short and it threw an exception. Later, I set the title manually with the ``title`` command -- maybe that command is broken, it did not set the title everywhere :-? 

Or maybe it is ok like this? I never received such messages :D

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/amihaiemil/docker-java-api/issues/38#issuecomment-372778005))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#38](https://github.com/amihaiemil/docker-java-api/issues/38) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/G6LPQQV2P?q=%7Bjob%3A%27gh%3Aamihaiemil%2Fdocker-java-api%2338%27%7D) (restricted area)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#41](https://github.com/amihaiemil/docker-java-api/issues/41) is still not solved; solved: [#42](https://github.com/amihaiemil/docker-java-api/issues/42).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#79](https://github.com/amihaiemil/docker-java-api/issues/79) is still not solved; solved: [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#87](https://github.com/amihaiemil/docker-java-api/issues/87) is still not solved; solved: [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42), [#79](https://github.com/amihaiemil/docker-java-api/issues/79).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#87](https://github.com/amihaiemil/docker-java-api/issues/87) is still not solved; solved: [#10](https://github.com/amihaiemil/docker-java-api/issues/10), [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42), [#79](https://github.com/amihaiemil/docker-java-api/issues/79).
